# Generated by Django 3.0.5 on 2020-05-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weDeliver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
    ]
